---
# Clone YOLO application repository from GitHub
# Dependencies: Git must be installed

- name: Clone YOLO repository
  ansible.builtin.git:
    repo: "https://github.com/Sally-N-Ngure/yoloIP2.git"
    dest: "/home/vagrant/yoloIP2"
    version: "master"
    update: yes
  become_user: "vagrant"
  tags:
    - repo
    - setup

- name: Set ownership of repository
  ansible.builtin.file:
    path: "/home/vagrant/yoloIP2"
    owner: "vagrant"
    group: "vagrant"
    recurse: yes
  tags:
    - repo
    - setup
