- name: Deploy YOLO on VM using Ansible
  hosts: all
  become: yes
  vars_files:
    - ansible/group_vars/all.yml
    - ansible/secrets.yml

  roles:
    - install_docker
    - install_git
    - clone_repo
    - network_deployment
    - backend_deployment
    - frontend_deployment